---

- name: EPEL Repository (RedHat)
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux {{ supervisor_epel_release }} - $basearch
    baseurl: "{{ supervisor_epel_baseurl }}"
    failovermethod: priority
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ supervisor_epel_gpgkey }}"

- name: Refresh yum cache
  command: yum makecache

- name: Install Packages (RedHat)
  yum:
    state: present
    name: "{{ item }}"
    enablerepo: "epel"
  with_items: "{{ supervisor_packages }}"

# Fix for Amazon 2015.03
- name: Amazon pip install supervisor
  pip:
    state: present
    name: "supervisor>=3.2,<4"
  when: ansible_distribution == 'Amazon'

# vi:ts=2:sw=2:et:ft=yaml
