---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- name: Include OS distribution vars
  include_vars: "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
  tags: always

- include: install.yml
  tags: supervisor_install

- include: config.yml
  tags: supervisor_config

- name: Start and Enable supervisor
  service:
    name="{{supervisor_service}}"
    enabled=yes
  when: supervisor_enabled

# vi:ts=2:sw=2:et:ft=yaml
